import type { NextComponentType, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

type FractalLinkProps = {
  href: string;
  imageSrc: string;
  title: string;
};

const FractalLink = ({ href, imageSrc, title }: FractalLinkProps) => {
  return (
    <div className={styles.gridItem}>
      <article className={styles.card}>
        <Link as={href} href={href}>
          <a className={styles.cardLink}></a>
        </Link>
        <div className={styles.squareImage}>
          <Image src={imageSrc} alt={title} layout="fill" />
        </div>

        <div className={styles.cardContent}>
          <h3>{title}</h3>
        </div>
      </article>
    </div>
  );
};

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.mainContent}>
        <h1>Fractal Garden</h1>
        <h2 id={styles.subtitle}>An Exhibition Of Mathematical Beauty</h2>
        <div className={styles.grid}>
          <FractalLink
            href="/mandelbrot"
            title="Mandelbrot Set"
            imageSrc="/assets/fractal-images/mandelbrot.png"
          />
          <FractalLink
            href="/barnsley-fern"
            title="Barnsley Fern"
            imageSrc="/assets/fractal-images/barnsley-fern.png"
          />
          <FractalLink
            href="/sierpinski-carpet"
            title="Sierpinski Carpet"
            imageSrc="/assets/fractal-images/sierpinski-carpet.png"
          />
          <FractalLink
            href="/l-system/index.html?fractal=lévy-curve"
            title="Lévy Curve"
            imageSrc="/assets/fractal-images/l-system-levy.png"
          />
          <FractalLink
            href="/l-system/index.html?fractal=fern-1"
            title="L-System Fern 1"
            imageSrc="/assets/fractal-images/l-system-fern-1.png"
          />
          <FractalLink
            href="/l-system/index.html?fractal=fern-2"
            title="L-System Fern 2"
            imageSrc="/assets/fractal-images/l-system-fern-2.png"
          />
          <FractalLink
            href="/l-system/index.html?fractal=fern-3"
            title="L-System Fern 3"
            imageSrc="/assets/fractal-images/l-system-fern-3.png"
          />
          <FractalLink
            href="/l-system/index.html?fractal=fern-4"
            title="L-System Fern 4"
            imageSrc="/assets/fractal-images/l-system-fern-4.png"
          />
          <FractalLink
            href="/l-system/index.html?fractal=board"
            title="Board"
            imageSrc="/assets/fractal-images/l-system-board.png"
          />
          <FractalLink
            href="/l-system/index.html?fractal=sierpinski-triangle"
            title="Sierpinski Triangle"
            imageSrc="/assets/fractal-images/l-system-sierpinski-triangle.png"
          />
          <FractalLink
            href="/fractal-tree"
            title="Fractal Tree"
            imageSrc="/assets/fractal-images/fractal-tree.png"
          />
          <FractalLink
            href="/l-system/index.html?fractal=quadratic-snowflake"
            title="Quadratic Snowflake"
            imageSrc="/assets/fractal-images/l-system-quadratic-snowflake.png"
          />
          {/*
          
          <div className="grid-item">
            <article className="card">
              <a
                className="card-link"
                href="/l-system/index.html?fractal=quadratic-snowflake"
              ></a>
              <img
                src="/assets/fractal-images/l-system-quadratic-snowflake.png"
                className="square-image"
                alt="l-system-quadratic-snowflake"
              />
              <div className="card-content">
                <h3>Quadratic Snowflake</h3>
              </div>
            </article>
          </div>

          <div className="grid-item">
            <article className="card">
              <a
                className="card-link"
                href="/l-system/index.html?fractal=koch-snowflake"
              ></a>
              <img
                src="/assets/fractal-images/l-system-koch-snowflake.png"
                className="square-image"
                alt="l-system-koch-snowflake"
              />
              <div className="card-content">
                <h3>Koch Snowflake</h3>
              </div>
            </article>
          </div>

          <div className="grid-item">
            <article className="card">
              <a
                className="card-link"
                href="/l-system/index.html?fractal=hilbert-curve"
              ></a>
              <img
                src="/assets/fractal-images/l-system-hilbert-curve.png"
                className="square-image"
                alt="l-system-hilbert-curve"
              />
              <div className="card-content">
                <h3>Hilbert Curve</h3>
              </div>
            </article>
          </div>

          <div className="grid-item">
            <article className="card">
              <a
                className="card-link"
                href="/l-system/index.html?fractal=sierpinski-square"
              ></a>
              <img
                src="/assets/fractal-images/l-system-sierpinski-square.png"
                className="square-image"
                alt="l-system-sierpinski-square"
              />
              <div className="card-content">
                <h3>Sierpinski Square</h3>
              </div>
            </article>
          </div>

          <div className="grid-item">
            <article className="card">
              <a
                className="card-link"
                href="/l-system/index.html?fractal=crystal"
              ></a>
              <img
                src="/assets/fractal-images/l-system-crystal.png"
                className="square-image"
                alt="l-system-crystal"
              />
              <div className="card-content">
                <h3>Crystal</h3>
              </div>
            </article>
  </div> */}
        </div>
      </main>
    </div>
  );
};

export default Home;
